services:
  - type: web
    name: tookit
    env: node
    buildCommand: PUPPETEER_SKIP_DOWNLOAD=true yarn install && NODE_OPTIONS='--max_old_space_size=4096' yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0