services:
  - type: web
    name: ticket-searcher
    env: node
    buildCommand: |
      set -ex
      # Configure environment
      yarn config set network-timeout 300000
      yarn config set legacy-peer-deps true
      
      # Create directories
      mkdir -p /opt/render/chrome
      mkdir -p /opt/render/.cache/puppeteer
      chmod -R 777 /opt/render/.cache/puppeteer
      
      # Install dependencies
      apt-get update -y
      apt-get install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 \
        libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 \
        libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 \
        libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
        libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
        libxss1 libxtst6 lsb-release wget xdg-utils unzip
      
      # Download and set up Chrome
      cd /opt/render/chrome
      wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dpkg -i google-chrome-stable_current_amd64.deb || apt-get -f install -y
      
      # Verify Chrome installation
      echo "Chrome version:"
      google-chrome-stable --version || true
      which google-chrome-stable || true
      ls -la /usr/bin/google-chrome* || true
      
      # Install project dependencies and build
      cd /opt/render/project/src
      yarn install --network-timeout 300000
      yarn build
    startCommand: yarn start
    nodeVersion: ">=18.0.0"
    envVars:
      - key: NODE_ENV
        value: production