services:
  - type: web
    name: ticket-searcher
    env: node
    buildCommand: |
      set -ex
      yarn config set network-timeout 300000
      yarn config set legacy-peer-deps true
      # Install chromium
      apt-get update -y
      apt-get install -y chromium
      # Check installation
      echo "Checking chromium installation:"
      which chromium
      ls -la /usr/bin/chromium* || true
      whereis chromium || true
      find /usr -name "chromium*" -type f 2>/dev/null || true
      # Setup directories
      mkdir -p /opt/render/.cache/puppeteer
      chmod -R 777 /opt/render/.cache/puppeteer
      # Install dependencies and build
      yarn install --network-timeout 300000
      yarn build
    startCommand: yarn start
    nodeVersion: ">=18.0.0"
    envVars:
      - key: NODE_ENV
        value: production