services:
  - type: web
    name: ticket-searcher
    env: node
    buildCommand: |
      set -ex
      yarn config set network-timeout 300000
      yarn config set legacy-peer-deps true
      
      # Install dependencies
      apt-get update
      apt-get install -y ca-certificates fonts-liberation unzip curl gnupg
      
      # Install Chrome
      curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get -y update && apt-get -y install google-chrome-stable
      
      # Verify installation
      google-chrome-stable --version
      which google-chrome-stable
      
      # Install dependencies and build
      yarn install --network-timeout 300000
      yarn build
    startCommand: yarn start
    nodeVersion: ">=18.0.0"
    envVars:
      - key: NODE_ENV
        value: production