services:
  - type: web
    name: ticket-searcher
    env: node
    buildCommand: |
      set -ex
      yarn config set network-timeout 300000
      yarn config set legacy-peer-deps true
      yarn install --network-timeout 300000
      yarn build
    startCommand: |
      apt-get update && \
      apt-get install -y wget gnupg && \
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
      apt-get update && \
      apt-get install -y google-chrome-stable && \
      export CHROME_EXECUTABLE_PATH=$(which google-chrome-stable) && \
      echo "Chrome installed at: $CHROME_EXECUTABLE_PATH" && \
      google-chrome-stable --version && \
      yarn start
    nodeVersion: ">=18.0.0"
    envVars:
      - key: NODE_ENV
        value: production