services:
  - type: web
    name: ticket-searcher
    env: node
    buildCommand: |
      set -ex
      yarn config set network-timeout 300000
      yarn config set legacy-peer-deps true
      
      # Install dependencies with sudo
      sudo apt-get update
      sudo apt-get install -y ca-certificates fonts-liberation unzip curl gnupg
      
      # Install Chrome with sudo
      sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      sudo echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
      sudo apt-get -y update
      sudo apt-get -y install google-chrome-stable
      
      # Verify installation
      sudo google-chrome-stable --version
      ls -la /usr/bin/google-chrome*
      
      # Create cache directory
      sudo mkdir -p /opt/render/.cache/puppeteer
      sudo chmod -R 777 /opt/render/.cache/puppeteer
      
      # Install dependencies and build
      yarn install --network-timeout 300000
      yarn build
    startCommand: yarn start
    nodeVersion: ">=18.0.0"
    envVars:
      - key: NODE_ENV
        value: production